# Generated by Django 2.2.14 on 2020-07-31 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hgfhfhg',
            field=models.ManyToManyField(blank=True, related_name='homepage_hgfhfhg', to='home.CustomText'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hgfhgfghf',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homepage_hgfhgfghf', to='home.HomePage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hgfhgfh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homepage_hgfhgfh', to=settings.AUTH_USER_MODEL),
        ),
    ]
